<?php
/**
 * Single comment markup.
 *
 * @package Webbooks
 *
 * @var array<string, mixed> $args
 */

$comment_data = $args['comment'] ?? null;
$classes      = (string) ( $args['classes'] ?? '' );
$reply_markup = (string) ( $args['reply_markup'] ?? '' );
if ( ! $comment_data instanceof WP_Comment ) {
	return;
}
?>
<li id="li-comment-<?php echo (int) $comment_data->comment_ID; ?>" class="comment-item <?php echo esc_attr( $classes ); ?>">
	<article id="comment-<?php echo (int) $comment_data->comment_ID; ?>" class="comment-body card">
		<div class="card-body">
			<div class="d-flex gap-3 align-items-start">
				<?php echo get_avatar( $comment_data, 64, '', '', array( 'class' => 'comment-author-avatar rounded-circle flex-shrink-0' ) ); // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- Avatar markup is generated by WordPress. ?>
				<div class="flex-grow-1 min-width-0">
					<p class="comment-meta mb-2">
						<strong><?php esc_html_e( 'Author:', 'webbooks' ); ?></strong> <?php echo esc_html( get_comment_author( $comment_data ) ); ?>
						<span aria-hidden="true">·</span>
						<time datetime="<?php echo esc_attr( get_comment_date( 'c', $comment_data ) ); ?>"><?php echo esc_html( get_comment_date( 'd.m.Y H:i', $comment_data ) ); ?></time>
					</p>
					<?php if ( '0' === (string) $comment_data->comment_approved ) : ?>
						<p class="comment-awaiting-moderation alert alert-warning py-2 mb-3"><?php esc_html_e( 'Your comment is awaiting moderation.', 'webbooks' ); ?></p>
					<?php endif; ?>
					<div class="comment-content mb-3"><?php comment_text( $comment_data ); ?></div>
					<?php echo wp_kses_post( $reply_markup ); ?>
				</div>
			</div>
		</div>
	</article>
